services:
  gateway:
    build:
      context: .          
      dockerfile: Dockerfile
    container_name: nginx-lua-gateway
    ports:
      - "8081:80"    # HTTP
      - "8443:443"   # HTTPS (host:container)
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./lua:/etc/openresty/lua:ro
      - ./keys:/etc/openresty/keys:ro
      - ./certs:/etc/openresty/certs:ro
    environment:
      - ADMIN_API_URL=${ADMIN_API_URL}
      - DEVICES_API_URL=${DEVICES_API_URL}
      - METRICS_API_URL=${METRICS_API_URL}
      - ADMIN_API_DOCS=${ADMIN_API_DOCS}
      - DEVICES_API_DOCS=${DEVICES_API_DOCS}
      - METRICS_API_DOCS=${METRICS_API_DOCS}
      - YOLO_API_URL=${YOLO_API_URL}
      - MOCK_ADAPTER_URL=${MOCK_ADAPTER_URL}
    command: /bin/sh -c "mkdir -p /var/log/nginx && openresty -g 'daemon off;'"
    restart: always

networks:
  gateway-net:
    driver: bridge
